/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InviteToken = IDL.Text;
export const ChatId = IDL.Text;
export const GroupId = IDL.Text;
export const GroupMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Text,
});
export const EncryptedMessage = IDL.Record({
  'id' : IDL.Text,
  'ciphertext' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Text,
});

export const idlService = IDL.Service({
  'checkInviteToken' : IDL.Func([InviteToken], [IDL.Bool], ['query']),
  'createChat' : IDL.Func([IDL.Text], [ChatId, InviteToken], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId, InviteToken], []),
  'getChatInfo' : IDL.Func(
      [ChatId, IDL.Text],
      [
        IDL.Record({
          'participants' : IDL.Vec(IDL.Text),
          'createdAt' : IDL.Int,
          'messageCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getGroupByToken' : IDL.Func([InviteToken], [GroupId], ['query']),
  'getGroupInfo' : IDL.Func(
      [GroupId],
      [
        IDL.Record({
          'participants' : IDL.Vec(IDL.Text),
          'name' : IDL.Text,
          'createdAt' : IDL.Int,
          'messageCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(GroupMessage)], ['query']),
  'getMessages' : IDL.Func([ChatId, IDL.Text], [IDL.Vec(EncryptedMessage)], []),
  'joinChat' : IDL.Func([InviteToken, IDL.Text], [ChatId], []),
  'joinGroup' : IDL.Func([InviteToken, IDL.Text], [GroupId], []),
  'sendGroupMessage' : IDL.Func([GroupId, IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([ChatId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InviteToken = IDL.Text;
  const ChatId = IDL.Text;
  const GroupId = IDL.Text;
  const GroupMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Text,
  });
  const EncryptedMessage = IDL.Record({
    'id' : IDL.Text,
    'ciphertext' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Text,
  });
  
  return IDL.Service({
    'checkInviteToken' : IDL.Func([InviteToken], [IDL.Bool], ['query']),
    'createChat' : IDL.Func([IDL.Text], [ChatId, InviteToken], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId, InviteToken], []),
    'getChatInfo' : IDL.Func(
        [ChatId, IDL.Text],
        [
          IDL.Record({
            'participants' : IDL.Vec(IDL.Text),
            'createdAt' : IDL.Int,
            'messageCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getGroupByToken' : IDL.Func([InviteToken], [GroupId], ['query']),
    'getGroupInfo' : IDL.Func(
        [GroupId],
        [
          IDL.Record({
            'participants' : IDL.Vec(IDL.Text),
            'name' : IDL.Text,
            'createdAt' : IDL.Int,
            'messageCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getGroupMessages' : IDL.Func(
        [GroupId],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ChatId, IDL.Text],
        [IDL.Vec(EncryptedMessage)],
        [],
      ),
    'joinChat' : IDL.Func([InviteToken, IDL.Text], [ChatId], []),
    'joinGroup' : IDL.Func([InviteToken, IDL.Text], [GroupId], []),
    'sendGroupMessage' : IDL.Func([GroupId, IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([ChatId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };