/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatId = string;
export interface EncryptedMessage {
  'id' : string,
  'ciphertext' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export type GroupId = string;
export interface GroupMessage {
  'id' : string,
  'content' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export type InviteToken = string;
export interface _SERVICE {
  'checkInviteToken' : ActorMethod<[InviteToken], boolean>,
  'createChat' : ActorMethod<[string], [ChatId, InviteToken]>,
  'createGroup' : ActorMethod<[string, string], [GroupId, InviteToken]>,
  'getChatInfo' : ActorMethod<
    [ChatId, string],
    {
      'participants' : Array<string>,
      'createdAt' : bigint,
      'messageCount' : bigint,
    }
  >,
  'getGroupByToken' : ActorMethod<[InviteToken], GroupId>,
  'getGroupInfo' : ActorMethod<
    [GroupId],
    {
      'participants' : Array<string>,
      'name' : string,
      'createdAt' : bigint,
      'messageCount' : bigint,
    }
  >,
  'getGroupMessages' : ActorMethod<[GroupId], Array<GroupMessage>>,
  'getMessages' : ActorMethod<[ChatId, string], Array<EncryptedMessage>>,
  'joinChat' : ActorMethod<[InviteToken, string], ChatId>,
  'joinGroup' : ActorMethod<[InviteToken, string], GroupId>,
  'sendGroupMessage' : ActorMethod<[GroupId, string, string], undefined>,
  'sendMessage' : ActorMethod<[ChatId, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];